- .github/workflows/ci.yaml
- package.json
This pull request adds the `ci.yaml` workflow to implement continuous integration for the application. This ensures that changes are validated and can be safely merged into the master branch.
> chore: add `ci.yaml` workflow

- src/app/login/page.tsx
- src/lib/@types/types.ts
- src/ui/globals.css
- src/ui/header/header-menu.tsx
- src/ui/header/header.tsx
This pull request enhances the header menu's styling and logic, addressing issues where state inconsistencies previously led to incorrect styles and rendering. Additionally, it refines navigation to homepage sections and improves CSS specificity for the blur effect.
Key changes:
- Add more advanced state to handle `matchMedia` and `menu toggle` in header
- Update colors on the login route
- Enhance blur effect rule
- Add navigation link to `about-us` section
> fix: resolve header conflicts

- src/middleware.ts
This pull request resolves an issue in the middleware where unauthenticated users were not correctly redirected to the login page due to an incorrect instance configuration. Key updates:
> fix: resolve redirect error in middleware

- .github/workflows/ci.yaml
- package.json
- pnpm-lock.yaml
- src/app/api/dashboards/samples/route.ts
- src/app/api/dashboards/zones/route.ts
- src/app/api/zones/route.ts
- src/app/dashboard/add/page.tsx
- src/app/dashboard/page.tsx
- src/lib/@types/props.ts
- src/lib/@types/types.ts
- src/lib/actions.ts
- src/lib/auth.ts
- src/lib/schemas.ts
- src/lib/services/dashboard.ts
- src/lib/types.d.ts
- src/ui/dashboard/table.tsx
- src/ui/header/loggin.tsx
- src/ui/session/login.tsx
Key changes:
- Update `jwt` and `session` objects in `next-auth`
- Add validation for fields in the `Add new sample`
- Install `zod`
- Add a `log out` button
> chore: enhance authentication and authorization

- src/app/api/dashboards/samples/route.ts
- src/app/api/dashboards/zones/route.ts
- src/lib/actions.ts
- src/lib/auth.ts
- src/lib/services/dashboard.ts
- src/ui/dashboard/samples/add-sample.tsx
This pull request enhances the route handlers by adding documentation and caching to improve performance and maintainability.
- Add caching to `POST`requests on the `api/dashboards/samples` endpoint to improve the performance
- Document route handlers to clarify functionality and usage
- Implement `revalidateTag` in `addSampleAction` request to ensure fresh data on updates
- Implement `revalidateTag` in `addSampleAction` request to ensure fresh data on updates
> chore: add documentation and caching for route handlers

- prisma/migrations/20241109170459_init/migration.sql
- prisma/migrations/20241109172300_init/migration.sql
- prisma/migrations/20241109173540_init/migration.sql
- prisma/schema.prisma
- src/app/api/v1/employees/[userId]/samples/route.ts
- src/app/api/v1/employees/[userId]/zones/route.ts
- src/app/api/v1/samples/route.ts
- src/app/api/v1/zones/route.ts
- src/lib/@types/props.ts
- src/lib/@types/types.ts
- src/lib/auth.ts
- src/lib/services/dashboard.ts
- src/ui/dashboard/filter.tsx
- src/ui/dashboard/samples/add-sample.tsx
- src/ui/dashboard/table.tsx
> chore: update database

- prisma/schema.prisma
This pull request runs `format` script
> chore: run format

- src/app/layout.tsx
- src/lib/@types/props.ts
- src/lib/@types/types.ts
- src/ui/footer.tsx
- src/ui/header/header-menu.tsx
- src/ui/header/header.tsx
This pull request enhances the rendering performance of the `Header` component, focusing on efficient state updates and optimizing user interactions.
- Refactored `Header` component to optimize state management, reducing unnecessary re-renders.
- Improved handling of state updates when navigating between sections.
- Integrated `Suspense` to manage component loading states for a smoother user experience.
> chore: optimize rendering in `Header` component

- .env.local.example
- README.md
This pull request introduces several changes in the README.md content file to  adding some sections and improving current sections
- Add sections for installation, cloning the repository, installing dependencies, tech stack and runnning application
- Improve content in structure section
> chore(docs): update `REAMDE.md` with project setup instructions

- package.json
- pnpm-lock.yaml
- src/lib/auth.ts
- src/lib/utils.ts
> feat: implement encryptation with `bcryptjs`

- src/app/api/auth/[...nextauth]/route.ts
- src/app/api/v1/companies/route.ts
- src/app/api/v1/employees/[userId]/Plants/route.ts
- src/app/api/v1/employees/[userId]/companies/route.ts
- src/app/api/v1/employees/[userId]/route.ts
- src/app/api/v1/employees/[userId]/samples/route.ts
- src/app/api/v1/employees/[userId]/users/route.ts
- src/app/api/v1/employees/[userId]/zones/route.ts
- src/app/api/v1/employees/[userId]/zonesByCompany/route.ts
- src/app/api/v1/plants/route.ts
- src/app/api/v1/roles/route.ts
- src/app/api/v1/samples/[sampleId]/route.ts
- src/app/api/v1/users/route.tsx
- src/lib/@types/types.ts
- src/lib/schemas.ts
- src/lib/types.d.ts
This pull request adds comprehensive documentation for the application's API route handlers, providing detailed information on HTTP request methods, parameters, expected responses, and usage guidelines.
> chore(docs): add documentation to route handlers

- src/app/api/v1/users/[userId]/samples/route.ts
- src/lib/actions.ts
- src/lib/schemas.ts
- src/ui/dashboard/samples/add-sample.tsx
This pull request resolves issues encountered when adding samples to the database. The primary fix involves updating the Zod schema to correctly validate the form data, ensuring all required fields are included for sample creation. Additionally, the `Input` component has been updated to allow decimal values by adjusting the `step` property.
> fix: resolve issue with adding samples to the database

- package.json
- pnpm-lock.yaml
This pull request improves environment variable handling and Prisma configuration in package.json. Key updates include:
- Configured environment variables in relevant scripts to properly recognize development and build environments.
- Adjusted Prisma script to ensure prisma:generate runs without errors.
- Improved script clarity to support better environment-specific functionality.
> chore: update environment variables and dependencies in `package.json`

- src/app/layout.tsx
- src/lib/data.json
- src/ui/dashboard/companies/add-company.tsx
- src/ui/dashboard/plants/add-plant.tsx
- src/ui/dashboard/plants/table.tsx
- src/ui/dashboard/users/add-user.tsx
- src/ui/dashboard/users/table.tsx
This pull request cleans up the codebase.
> chore: clean up code

- src/app/api/v1/users/[userId]/zonesByCompany/route.ts
- src/lib/@types/props.ts
- src/ui/dashboard/zones/table.tsx
It is created so that in 'zones' the plant name appears instead of the ID.
> chore: update plant's name

- src/app/api/v1/users/[userId]/plants/route.ts
- src/app/api/v1/users/[userId]/users/route.ts
- src/lib/@types/props.ts
- src/lib/actions.ts
- src/ui/dashboard/users/table.tsx
This PR is created to display the user's phone number with their respective role as text, rather than showing the IDs
> feat: add users' phones and roles

- prisma/migrations/20241119154220_init/migration.sql
- prisma/schema.prisma
This pull request adds a new model in `schema.prisma` file
> chore: add `ProjectsOnUsers` model

- src/lib/@types/types.ts
- src/lib/actions.ts
- src/lib/services/clients.ts
- src/lib/services/projects.ts
- src/ui/dashboard/companies/add-company.tsx
- src/ui/dashboard/plants/add-plant.tsx
- src/ui/dashboard/usersPlants/add-userPlants.tsx
This pull request was created to fix the urls of actions and services
> fix: change urls of actions and services

- src/app/api/v1/projects/route.ts
- src/app/api/v1/zones/route.ts
- src/lib/actions.ts
- src/ui/dashboard/zones/add-zones.tsx
This PR was created to add validation allowing zones with the same coordinates to be added.
> fix: apply validation to zones

- src/app/dashboard/samples/[sampleId]/page.tsx
- src/app/dashboard/samples/page.tsx
- src/lib/actions.ts
- src/lib/utils.ts
… protection thickness
Implemented version 2 of the sample with criteria for evaluating protection thickness, aligned with the AS/NZS 2041.1:2011 standard.
> feat: implemented version 2 of the sample with criteria for evaluatin

- src/app/api/v1/projects/route.ts
- src/app/api/v1/zones/route.ts
This pr was created to add validations, which is that there cannot be two zones and projects with the same name
> chore: add validation the names in zones and projects

- prisma/migrations/20241207194050_init/migration.sql
- prisma/migrations/20241207194434_init/migration.sql
- prisma/migrations/20241207200747_init/migration.sql
- prisma/schema.prisma
This pull request migrates and updates the schema of the database in the `schema.prisma` file. It includes updates to the names of the models, adds new attributes, and incorporates other necessary changes. The following script demonstrates the result for MySQL.
- Update model names in `schema.prisma`
- Add new attributes
- Apply other necessary schema changes
The new database: 
```mysql
create database webtool;
use webtool;
-- Crear la tabla para la enumeración State
CREATE TABLE StateEnum (
State ENUM('ACTIVE', 'INACTIVE') NOT NULL
);
-- Crear la tabla para la enumeración ActionType
CREATE TABLE ActionTypeEnum (
ActionType ENUM('INSERT', 'UPDATE', 'DELETE') NOT NULL
);
-- Tabla Picture
CREATE TABLE Picture (
idPicture INT AUTO_INCREMENT PRIMARY KEY,
idStakeholder VARCHAR(255) NOT NULL, …
```
> chore: migrate database in `schema.prisma` file

- package.json
- pnpm-lock.yaml
- src/app/api/v1/contact-people/[contactPersonId]/cookies/route.ts
- src/app/api/v1/contact-people/[contactPersonId]/projects/route.tsx
- src/app/dashboard/page.tsx
- src/app/dashboard/projects/page.tsx
- src/app/pick-your-project/page.tsx
- src/lib/@types/props.ts
- src/lib/services/contact-people.ts
- src/lib/services/index.ts
- src/lib/services/projects.ts
- src/lib/services/stakeHolders.ts
- src/lib/utils.ts
- src/middleware.ts
- src/ui/common/form.tsx
- src/ui/dashboard/index/card.tsx
- src/ui/dashboard/projects/add-new-project.tsx
- src/ui/dashboard/projects/add-plant.tsx
- src/ui/dashboard/projects/table.tsx
- src/ui/globals.css
- src/ui/pick-your-project/project.tsx
> feat: add `pick-your-project` route

- package.json
- pnpm-lock.yaml
- src/app/page.tsx
- src/lib/@types/props.ts
- src/lib/types.d.ts
- src/ui/common/filter.tsx
- src/ui/common/menu-routes.tsx
- src/ui/common/select-generic.tsx
- src/ui/common/select.tsx
- src/ui/dashboard/index/card.tsx
- src/ui/header/header-menu.tsx
- src/ui/header/header.tsx
- src/ui/index/products/product.tsx
- src/ui/pdf.tsx
- src/ui/session/login.tsx
This pull request resolves the issue of improper rendering in the header and header-menu components, which sometimes caused the components to not render correctly, prompting users to refresh the page. The solution involved importing the same component twice: once for mobile devices and once for desktop devices, with separate logic for each.
Additionally, the logic for framer-motion animations was re-implemented on both the server side and the client side. One of the reasons for updating framer-motion was its incompatibility with React and React-DOM 19, which led to some attributes not being recognized. Finally, the priority property was added to the images.
- Update `framer-motion@12.0.0-alpha.2`
- Update `react` and `react-dom`
These changes improve the rendering performance and …
> fix: resolve bad render in header

- .eslintrc.json
- next.config.ts
- src/app/api/v1/cookies/route.ts
- src/app/dashboard/address/add/page.tsx
- src/app/dashboard/layout.tsx
- src/app/dashboard/position-soil-datas/page.tsx
- src/lib/@types/types.ts
- src/lib/services/cookies.ts
- src/lib/utils.ts
- src/middleware.ts
- src/ui/common/menu-routes.tsx
- src/ui/dashboard/contact-people/add-contact-person.tsx
- src/ui/dashboard/fields/add-fields.tsx
- src/ui/dashboard/menu.tsx
- src/ui/dashboard/position-soil-datas/add-position-soil-datas.tsx
- src/ui/dashboard/postion-datas/add-position-data.tsx
- src/ui/dashboard/projects/add-project.tsx
- src/ui/dashboard/stake-holders/add-stake-holders.tsx
- src/ui/header/avatar.tsx
This pull request updates the logic related to the `control-base-access-control RBAC` to work with roles and also updates the middleware to enhance functionality.
> chore: update `control-base-access-control` and `middleware`

- src/app/dashboard/fields/[idProject]/page.tsx
- src/app/dashboard/projects/page.tsx
- src/lib/@types/props.ts
- src/lib/utils.ts
- src/ui/dashboard/pick-project/project.tsx
- src/ui/dashboard/samples/table-compiled.tsx
This pr was created to implement a table which has the average of the values ​​of the samples made
> chore: implemnt table results projects

- src/ui/dashboard/projects/add-layout-project.tsx
- src/ui/dashboard/projects/add-layout-pvstructures-project.tsx
- src/ui/dashboard/projects/add-project.tsx
This pr was created to make the layout
> chore:added layout to projects
